// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compress(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Compress'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}
